spring:
  application:
    name:SERVICE-REGISTRY
  config:
    import:
      configserver: http://localhost:8085

server:
  port: 8761

eureka:
  client:
    register-with-eureka: false
    fetch-registry: false