server:
  port: 8081

spring:
  datasource:
    url: jdbc:postgresql://localhost:5432/user
    username: postgres
    password: password1
  jpa:
    properties:
      hibernate.dialect: org.hibernate.dialect.PostgreSQLDialect
    hibernate:
      ddl-auto: update